version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000/api
    restart: unless-stopped
    networks:
      - app-network

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5080:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=assistente_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=assistente_db
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    networks:
      - app-network

  # MySQL Database
  db:
    image: mysql:8.0
    ports:
      - "3380:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=assistente_db
      - MYSQL_USER=assistente_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data: